### ISSUE TITLE
0610 - Todo list

### ISSUE THREAD

**Issue by anso33** [cozy-for-mom/cozy_for_mom_frontend#55]
✅ 실시간 업데이트 문제는 비동기 처리때문에 발생하는 이슈였음!
: 비동기 함수(API)로 요청 시, await 키워드를 사용하여 상태 업데이트 전에 비동기 작업이 완료되도록 해야 한다.

- [x] 회원가입 프로세스에서 다음 버튼 활성화시키기
- [x] 날짜 입력할 때 . 안적어도 되도록 수정하기
- [x] 다태아 등록할 때 컨테이너 박스로 했더니 짤림. 팝업으로 변경하기
- [x] 회원가입하고 main으로 안넘어감
- [x] 달력에서 팝업에 띠가 생김? -> elevation 속성을 0.0으로 설정하여 해결
- [x] #56
- [x] 식단 등록하고 이미지 업로드 될 동안 링 같은 표시 추가하기 
- [x] 영양제 실시간으로 수정해야함 (?)
- [x] 모든 기능에 대해서 변화가 화면에 바로 반영되도록 수정해야함.
- [x] 체중 필드값 딜레이
- [x] 식단 수정도 촬영/앨범 선택 모달 추가
- [x] 알림이랑 영양제 알림 화면 - 디자인 수정 반영하기 
- [x] 기본으로 데이터 박아놓은 화면 정리하기 
- [x] 알림 도메인 API 연동하기 
- [x] 알림 시간 위젯 적는 방식으로 변경하기 
- [x] 건강 그래프(체중, 혈당) 주간 월간 그래프 연동하기 
- [x] 태아 메인에 아이 이미지 반영하기 (누르면 랜덤 바뀌도록? 아님 메인페이지 접속할때마다 랜덤으로?) 👉 글자색도 변경하기
- [x] 태아 메인 스크롤 안됨
- [x] 태아 메인 페이지에 API 응답 데이터로 그리도록 수정하기 
- [x] 메인페이지 배경 수정 후로 바꾸기 (아침/점심/저녁 나눠서) 👉 글자색도 변경하기
- [x] 모든 등록 버튼 -> 활성화/비활성화 기능 제대로 구현하기 (비활일때, 색상뿐만 아니라 API 요청을 안보내도록)
- [x] 모든 페이지 글자색, 크기, 굵기 등 확인하기 🔺
- [x] 모든 텍스트 필드 키보드타입 지정하기

---

- [x] 성장보고서 다태아일 때 한번 확인해봐야할 듯 
- [x] 성장보고서 사진 업로드하도록 해야함. (식단 따라하기) --> 이것땜에 저장을 못함
- ~성장보고서 값 리셋되는 이슈 해결해야함. 시뮬레이터 키보드로 하면 리셋됨 (영양제도 같은이슈있었음. 이거처럼 해결하면 될듯)~
- [x] 성장보고서 요청바디에 babyProfileId 어디갔어. 산모 정보 조회할 때 babyProfileId 로컬스토리지에 저장해두기,!!
---
코지로그

- [x] 코지로그 스크롤바 변경된 버전 반영해야함.
- [x] 코지로그 사진추가 하나밖에 안됨...
- [x] 코지로그 공개/비공개 에러남
- [x] 코지로그 create api 어디갔어;;
- [x] 코지로그 수정할수있는 더보기 버튼 사라짐.
- [x] 코지로그 삭제 안됨 (편집화면에서 삭제가 안됨, 단일 삭제는 됨)
- [x] 코지로그 버튼들 왼쪽으로 치우쳐져있는 거 고치기;;

검색
- [x] 검색 자동검색이 바로 안뜸. 돌아올때 setState한번해야할듯
- [x] 최근 검색 눌렀을 . 때 아무 반응 없음. ;;

----
내정보
- [x] 프로필 수정 완료하고나서, (완료 알림 띄워야하나?) 내프로필 메인페이지로 이동시키기!
- [x] 프로필 사진업로드왜안돼
- [x] 내정보 (다른페이지인듯)에서 코지로그, 스크랩내역 버튼 동작안됨
- [x] 태아 추가하기 - 뒤로가기없음.
- [x] 태아 추가하기 - 출산예정일 키보드입력으로 변경
- [x] 태아 추가하기 - 사진 크롭?
- [x] 로그아웃, 탈퇴 버튼 복구 / API 연동해야함
- [x] 만나는날 D-79
---

- [x] 다음검진일 등록하는거 해야함

---
알림
- [ ] 푸시 알림 대응

---
태아 메인

- [x] 성장일지 기록해보세요 배너 -> 성장보고서 페이지 연결

---
산모 메인

- [x] 배너 디자인 수정 버전으로 변경 -> 백엔드 API 되기 전까지 혈당/영양제 중 하나로 현재 시간과 가장 가까운 알림으로 보여주기(시간/title)

---

회원가입

- [x] 스플래시 화면 (탈퇴 하고도 보여져야함. 그냥 reset느낌)

---

6/24일까지 회원가입 -> 메인페이지 프로세스 완료(채경), 성장보고서 버그 고치기(아영)

### 0701 TODO
- 코지로그, 검색 - 문아영 (+ 할수있으면 내정보)
- [x] 영양제(단일), 혈당(단일) - 채경언니  (혈당 그래프 뺴고)
- [x] 애플로그인 확인! - 채경언니

++
- [x] 다음검진일 API 

---
### 0708 TODO
- [x] 혈당 기간별 조회 페이지의 평균 혈당 카드 수정, 이메일 페이지 수정, 체중, 식단 이미지 링 (산모 부분 마무리 먼저) - 채경
- 혈당, 영양제 알림 카드 디자인 수정 -> 할 수 있으면!
- 코지로그 마무리, 내정보, 다음검진일까지? -> 아영

### 0715 TODO
- [x] 아영: 내정보 마무리 
- [ ] 아영: 태아 추가하기 API 완성하고, 성장보고서 다태아일 때 한번 확인하기
- [x] 아영: 다음검진일 API 
- [ ] 아영: 푸시 알림 대응
- [x] 아영: 성장일지 기록해보세요 배너 -> 성장보고서 페이지 연결
- [x] 채경: 알림이랑 영양제 알림 화면 - 디자인 수정 반영하기 
- [x] 채경: 알림 도메인 API 연동
- [x] 채경: 체중 필드값 딜레이
- [x] 채경: 식단 수정도 촬영/앨범 선택 모달 추가

### 0721
- [x] 산모페이지 - 영양제/혈당 구분할 수 있는 응답 필드 추가 plz~~ :pray:  @ck-pp @anso33 
  - [x] null일 떄는 기본문구로 보여주도록 하기 @ck-pp
- [x] 체중 입력 valid처리 (ex. 57..5)  (기존에 반영헀는데 코드가 사라진듯) 시간나면.. @ck-pp 
- [x] 성장보고서 다둥이일때 상세페이지 구분이 안됨. @ck-pp
- [ ] 다둥이 일 때 성장보고서 목록이 안보임 @ayoung0073 ??
- [ ] 코지로그 빈 목록이 내려옴 @anso33
- [ ] 세번째 탭 내 프로필 사진이 안나옴 @ayoung0073 
- [x] 태아 추가. 성공하고나서 이전 페이지로 이동! @ayoung0073 👉 이거 내가 했으 (@ck-pp)
- [ ] 최신순/댓글순 잘동작하는지 추가확인 필요함. @anso33 추가 확인: @ayoung0073 
- [ ] 검색결과없는 경우, 문구 변경 @ayoung0073 
- [x] 로그아웃/탈퇴 하드코딩되어있는 . 거 수정하기. (간편로그인 라디오버튼도 없애기) @ck-pp 
- [ ] 푸시 알림 진행 @ayoung0073 
- [x] 스플래쉬 화면 
- [ ] Welcome Screen 연결 @ck-pp

**Comment by ayoung0073** [comment]
```
"id": 32
"title": "철분",
"isActive": true,
"notifyAt": [ "one hour ago" ],
"targetTimeAt": [ "18:00" ],
"daysOfWeek": ["mon", "wed", "fri"]
```
